apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blue-ds
  namespace: k3s-arm-demo
spec:
  selector:
    matchLabels:
      app: blue-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-ds
      name: blue-ds
    spec:
      containers:
      - name: blue-ds
        image: mak3r/rpi-led:latest
        args: ["blink2.sh", "5"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev/gpiomem
            name: gpio4
      restartPolicy: Always
      volumes:
      - name: gpio4
        hostPath:
          path: /dev/gpiomem
